export const PERMISSIONS = {
  // 1. Dashboard & Reports
  DASH_VIEW_ADMIN: "DASH_VIEW_ADMIN",
  DASH_VIEW_TEAM: "DASH_VIEW_TEAM",
  DASH_VIEW_SELF: "DASH_VIEW_SELF",
  REP_VIEW_ORG: "REP_VIEW_ORG",
  REP_VIEW_PAY: "REP_VIEW_PAY",

  // 2. Core HR & Org Setup
  ORG_CONFIG_DEPT: "ORG_CONFIG_DEPT",
  ORG_CONFIG_DESIG: "ORG_CONFIG_DESIG",
  ORG_CONFIG_GRADE: "ORG_CONFIG_GRADE",
  EMP_CREATE: "EMP_CREATE",
  EMP_VIEW_ALL: "EMP_VIEW_ALL",
  EMP_UPDATE: "EMP_UPDATE",
  EMP_DELETE: "EMP_DELETE", // Usually restricted to Admin
  EMP_LIFECYCLE_PROMO: "EMP_LIFECYCLE_PROMO",
  EMP_LIFECYCLE_TRANS: "EMP_LIFECYCLE_TRANS",
  EMP_LIFECYCLE_TERM: "EMP_LIFECYCLE_TERM",

  // 3. Attendance Management
  ATT_CONFIG_SHIFT: "ATT_CONFIG_SHIFT",
  ATT_CONFIG_HOLIDAY: "ATT_CONFIG_HOLIDAY",
  ATT_SCHEDULE_CREATE: "ATT_SCHEDULE_CREATE",
  ATT_VIEW_TEAM: "ATT_VIEW_TEAM",
  ATT_VIEW_SELF: "ATT_VIEW_SELF",
  ATT_REALTIME_AI: "ATT_REALTIME_AI", 
  ATT_CORRECTION_APPROVE: "ATT_CORRECTION_APPROVE",
  ATT_CORRECTION_APPLY: "ATT_CORRECTION_APPLY",

  // 4. Payroll Management
  PAY_CONFIG_ELEMENTS: "PAY_CONFIG_ELEMENTS",
  PAY_CONFIG_TAX: "PAY_CONFIG_TAX",
  PAY_PROCESS_SALARY: "PAY_PROCESS_SALARY",
  PAY_GENERATE_PAYSLIP: "PAY_GENERATE_PAYSLIP",
  PAY_DISBURSE_BANK: "PAY_DISBURSE_BANK",
  PAY_VIEW_ALL_LEDGER: "PAY_VIEW_ALL_LEDGER",
  PAY_TAX_COMPLIANCE: "PAY_TAX_COMPLIANCE",

  // 5. Self-Service (ESS/MSS)
  ESS_PROFILE_EDIT: "ESS_PROFILE_EDIT",
  ESS_LEAVE_APPLY: "ESS_LEAVE_APPLY",
  ESS_LATE_APPLY: "ESS_LATE_APPLY",
  ESS_LOAN_APPLY: "ESS_LOAN_APPLY",
  ESS_ATT_VIEW: "ESS_ATT_VIEW",
  ESS_PAYSLIP_VIEW: "ESS_PAYSLIP_VIEW",
  MSS_LEAVE_APPROVE: "MSS_LEAVE_APPROVE",
  MSS_LATE_APPROVE: "MSS_LATE_APPROVE",
  MSS_TEAM_ATT_VIEW: "MSS_TEAM_ATT_VIEW",

  // 6. PF & Gratuity
  PF_CONFIG_RULES: "PF_CONFIG_RULES",
  PF_PROCESS_CONTRIB: "PF_PROCESS_CONTRIB",
  PF_LOAN_APPROVE: "PF_LOAN_APPROVE",
  PF_VIEW_STATEMENT: "PF_VIEW_STATEMENT",
  GRAT_CONFIG_FORMULA: "GRAT_CONFIG_FORMULA",
  GRAT_PROCESS_PROVISION: "GRAT_PROCESS_PROVISION",
  GRAT_SETTLE: "GRAT_SETTLE",
  GRAT_VIEW_STATEMENT: "GRAT_VIEW_STATEMENT",

  // 7. Loan & Advance
  LOAN_CAT_MANAGE: "LOAN_CAT_MANAGE",
  LOAN_APPROVE_TEAM: "LOAN_APPROVE_TEAM",
  LOAN_VIEW_LEDGER: "LOAN_VIEW_LEDGER",

  // 8. Document Management
  DOC_ORG_MANAGE: "DOC_ORG_MANAGE",
  DOC_EMP_MANAGE: "DOC_EMP_MANAGE",
  DOC_VIEW_TEAM: "DOC_VIEW_TEAM",
  DOC_VIEW_SELF: "DOC_VIEW_SELF",

  // 9. Communication & Settings
  COMM_NOTIFY_SEND: "COMM_NOTIFY_SEND",
  SYS_SETTINGS_MANAGE: "SYS_SETTINGS_MANAGE"
};